=== brunoNetId/FusePoC20160217/UC2/src/main/resources/schemas/customers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ListCustomers">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="customer" type="typeCustomer"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="typeCustomer">
		<xs:sequence>
			<xs:element maxOccurs="1" name="name" type="xs:string"/>
			<xs:element maxOccurs="1" name="address" type="xs:string"/>
			<xs:element maxOccurs="1" name="email" type="xs:string"/>
			<xs:element maxOccurs="1" name="country" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="user|partner"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== brunoNetId/FusePoC20160217/UC2/src/data/privateCustomers.xml
<?xml version="1.0" encoding="UTF-8"?>
<ListCustomers xsi:noNamespaceSchemaLocation="/home/developer/workspaceTraining/UC2/src/main/resources/schemas/customers.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
       <customer  type="user">
              <name>John</name>
              <address>King's st.</address>
              <email>John@king.st</email>
              <country>UK</country>
          </customer>
       <customer  type="partner">
              <name>A</name>
              <address>5th av.</address>
              <email>a@5th.av</email>
              <country>US</country>
          </customer>
       <customer type="user">
              <name>Lucy</name>
              <address>Newcourt St.</address>
              <email>lucy@newcourt.st</email>
              <country>UK</country>
          </customer>
   </ListCustomers>
